name: example
description: Flutter ResponsiveHelper Package Example

version: 1.0.0

environment:
sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  responsive_helper:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true