name: responsive_helper
description: ResponsiveHelper package helps you to make your app responsive
version: 1.0.0
author: Yousef Roshandel <yousef.r1999@gmail.com>
homepage: https://github.com/YRlp98/responsive_helper

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
